name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.1"
      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
        run: |
          curl -fsSL https://vercel.com/download -o vercel
          chmod +x vercel
          ./vercel --token $VERCEL_API_TOKEN --prod --confirm
